name: biponi_vendor
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.3
#  fancy_bottom_navigation: ^0.3.3
  salomon_bottom_bar: ^3.3.1
  dropdown_search: ^4.0.1
  toggle_switch: ^2.0.1
  flutter_switch: ^0.3.2
  image_picker: ^0.8.4+5
  image_cropper: ^2.0.3
  flutter_image_compress: ^1.1.0
  flutter_svg: ^0.23.0+1
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  get_storage: ^2.0.3
  google_fonts: ^3.0.0
  firebase_core:
  cloud_firestore:
  firebase_storage:
  firebase_messaging:
  timeago:
  intl: ^0.17.0
  dropdown_button2: ^1.1.1
  flutter_html: ^2.2.1
  url_launcher: ^6.0.20
  fancy_bottom_navigation_2: ^0.3.5

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

